### ISSUE TITLE
Ajouter un rôle "photographe"

### ISSUE THREAD

**Issue by clemlatz** [elytre/fusion#30]
Pour Béton rouge :

```yaml
    contributors:
      - name: Olivier Lavigne
        role: Cover artist
      - name: Apo Genc
        role : Photographier
```
